### ISSUE TITLE
NoSuchMethodError: The getter 'length' was called on null.

### ISSUE THREAD

**Issue by limit7412** [limit7412/slack_to_jira#13]
eventには必ずbodyがあるわけではないようなのでnullチェックを入れる

**Comment by limit7412** [comment]
```
NoSuchMethodError: The getter 'length' was called on null.
Receiver: null
Tried calling: length
#0      _parseJson (dart:convert-patch/convert_patch.dart:30)
#1      JsonDecoder.convert (dart:convert/json.dart:495)
#2      JsonCodec.decode (dart:convert/json.dart:153)
#3      main.<anonymous closure> (file:///work/src/main.dart:10)
#4      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:45)
#5      main.<anonymous closure> (file:///work/src/main.dart:7)
#6      lambdaHandler (file:///work/src/runtime.dart:20)
#7      _RootZone.runUnary (dart:async/zone.dart:1381)
#8      _FutureListener.handleValue (dart:async/future_impl.dart:139)
#9      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680)
#10     Future._propagateToListeners (dart:async/future_impl.dart:709)
#11     Future._completeWithValue (dart:async/future_impl.dart:524)
#12     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32)
#13     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290)
#14     _withClient (package:http/http.dart:0)
#15     _RootZone.runUnary (dart:async/zone.dart:1381)
#16     _FutureListener.handleValue (dart:async/future_impl.dart:139)
#17     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680)
#18     Future._propagateToListeners (dart:async/future_impl.dart:709)
#19     Future._completeWithValue (dart:async/future_impl.dart:524)
#20     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554)
#21     _microtaskLoop (dart:async/schedule_microtask.dart:43)
#22     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52)
#23     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118)
#24     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175)
```
